name = "tg-anti-spam-worker"
main = "src/index.ts"
compatibility_date = "2026-01-10"

# KV namespace binding for state storage
[[kv_namespaces]]
binding = "SPAM_STATE"
id = "f8c6be32d1f84fdea52cb89a2266f3d8"
preview_id = "7e2b85f85800450b9af21ab5d06e25b8"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[vars]
BOT_USERNAME = "cf_antispam_bot"